package net.plushified;

import net.fabricmc.api.ClientModInitializer;
import net.fabricmc.api.EnvType;
import net.fabricmc.api.Environment;
import net.fabricmc.fabric.api.blockrenderlayer.v1.BlockRenderLayerMap;
import net.minecraft.client.render.RenderLayer;
import net.minecraft.client.render.block.entity.BlockEntityRendererFactories;

import net.minecraft.util.Identifier;
import net.plushified.renderer.block.*;
import static net.plushified.registry.BlockEntityRegistry.*;
import static net.plushified.registry.BlockRegistry.*;

@Environment(EnvType.CLIENT)
public class PlushifiedClient implements ClientModInitializer {
	@Override
	public void onInitializeClient() {

		Plushified.LOGGER.info("OMG! Initializing Client...");

		BlockRenderLayerMap.INSTANCE.putBlock(ALEXNOMPE_PLUSHIE, RenderLayer.getTranslucent());
		BlockRenderLayerMap.INSTANCE.putBlock(ARUYUKI_PLUSHIE, RenderLayer.getTranslucent());
		BlockRenderLayerMap.INSTANCE.putBlock(BADBOYHALO_PLUSHIE, RenderLayer.getTranslucent());
		BlockRenderLayerMap.INSTANCE.putBlock(BLACKHOLE_PLUSHIE, RenderLayer.getTranslucent());
		BlockRenderLayerMap.INSTANCE.putBlock(BRIM_PLUSHIE, RenderLayer.getTranslucent());
    	BlockRenderLayerMap.INSTANCE.putBlock(CHECKGOODMAN_PLUSHIE, RenderLayer.getTranslucent());
    	BlockRenderLayerMap.INSTANCE.putBlock(CLOWNPIERCE_PLUSHIE, RenderLayer.getTranslucent());
    	BlockRenderLayerMap.INSTANCE.putBlock(DEB_PLUSHIE, RenderLayer.getTranslucent());
    	BlockRenderLayerMap.INSTANCE.putBlock(DIANSU_PLUSHIE, RenderLayer.getTranslucent());
    	BlockRenderLayerMap.INSTANCE.putBlock(DLZ_PLUSHIE, RenderLayer.getTranslucent());
    	BlockRenderLayerMap.INSTANCE.putBlock(DOCTOR4T_PLUSHIE, RenderLayer.getTranslucent());
    	BlockRenderLayerMap.INSTANCE.putBlock(DURAWKA_PLUSHIE, RenderLayer.getTranslucent());
    	BlockRenderLayerMap.INSTANCE.putBlock(EBONI_PLUSHIE, RenderLayer.getTranslucent());
    	BlockRenderLayerMap.INSTANCE.putBlock(FELIKTON_PLUSHIE, RenderLayer.getTranslucent());
    	BlockRenderLayerMap.INSTANCE.putBlock(FEREDEN_PLUSHIE, RenderLayer.getTranslucent());
    	BlockRenderLayerMap.INSTANCE.putBlock(FINEK_PLUSHIE, RenderLayer.getTranslucent());
    	BlockRenderLayerMap.INSTANCE.putBlock(GOOSE_PLUSHIE, RenderLayer.getTranslucent());
    	BlockRenderLayerMap.INSTANCE.putBlock(LAMPCAT_PLUSHIE, RenderLayer.getTranslucent());
    	BlockRenderLayerMap.INSTANCE.putBlock(LUX_PLUSHIE, RenderLayer.getTranslucent());
    	BlockRenderLayerMap.INSTANCE.putBlock(MASK_PLUSHIE, RenderLayer.getTranslucent());
    	BlockRenderLayerMap.INSTANCE.putBlock(MODDY_PLUSHIE, RenderLayer.getTranslucent());
    	BlockRenderLayerMap.INSTANCE.putBlock(NIKI_PLUSHIE, RenderLayer.getTranslucent());
    	BlockRenderLayerMap.INSTANCE.putBlock(NOVIKONY_PLUSHIE, RenderLayer.getTranslucent());
    	BlockRenderLayerMap.INSTANCE.putBlock(OBSI_PLUSHIE, RenderLayer.getTranslucent());
    	BlockRenderLayerMap.INSTANCE.putBlock(PHILZA_PLUSHIE, RenderLayer.getTranslucent());
    	BlockRenderLayerMap.INSTANCE.putBlock(PWGOOD_PLUSHIE, RenderLayer.getTranslucent());
    	BlockRenderLayerMap.INSTANCE.putBlock(R4TMAID_PLUSHIE, RenderLayer.getTranslucent());
    	BlockRenderLayerMap.INSTANCE.putBlock(RANBOO_PLUSHIE, RenderLayer.getTranslucent());
    	BlockRenderLayerMap.INSTANCE.putBlock(RESOTA_PLUSHIE, RenderLayer.getTranslucent());
    	BlockRenderLayerMap.INSTANCE.putBlock(SQUIDDO_PLUSHIE, RenderLayer.getTranslucent());
    	BlockRenderLayerMap.INSTANCE.putBlock(STALIN_PLUSHIE, RenderLayer.getTranslucent());
    	BlockRenderLayerMap.INSTANCE.putBlock(TECHNO_PLUSHIE, RenderLayer.getTranslucent());
    	BlockRenderLayerMap.INSTANCE.putBlock(TUVIKU_PLUSHIE, RenderLayer.getTranslucent());
    	BlockRenderLayerMap.INSTANCE.putBlock(VERYLOUDER_PLUSHIE, RenderLayer.getTranslucent());
    	BlockRenderLayerMap.INSTANCE.putBlock(VMUTED_PLUSHIE, RenderLayer.getTranslucent());
    	BlockRenderLayerMap.INSTANCE.putBlock(WINSWEEP_PLUSHIE, RenderLayer.getTranslucent());
    	BlockRenderLayerMap.INSTANCE.putBlock(ZMEEC_PLUSHIE, RenderLayer.getTranslucent());
    	BlockRenderLayerMap.INSTANCE.putBlock(ZMEEVIG_PLUSHIE, RenderLayer.getTranslucent());
    	BlockRenderLayerMap.INSTANCE.putBlock(JEREMI_PLUSHIE, RenderLayer.getTranslucent());
    	BlockRenderLayerMap.INSTANCE.putBlock(NUROFEN_PLUSHIE, RenderLayer.getTranslucent()); //this comment is autogenerated

		BlockEntityRendererFactories.register(ALEXNOMPE_PLUSHIE_BLOCK_ENTITY,
				context -> new PlushieRenderer(Identifier.of(Plushified.MOD_ID, "alexnompe_plushie")));
		BlockEntityRendererFactories.register(ARUYUKI_PLUSHIE_BLOCK_ENTITY,
				context -> new PlushieRenderer(Identifier.of(Plushified.MOD_ID, "aruyuki_plushie")));
		BlockEntityRendererFactories.register(BADBOYHALO_PLUSHIE_BLOCK_ENTITY,
				context -> new PlushieRenderer(Identifier.of(Plushified.MOD_ID, "badboyhalo_plushie")));
		BlockEntityRendererFactories.register(BLACKHOLE_PLUSHIE_BLOCK_ENTITY,
				context -> new PlushieRenderer(Identifier.of(Plushified.MOD_ID, "blackhole_plushie")));
        BlockEntityRendererFactories.register(BRIM_PLUSHIE_BLOCK_ENTITY,
				context -> new PlushieRenderer(Identifier.of(Plushified.MOD_ID, "brim_plushie")));
        BlockEntityRendererFactories.register(CHECKGOODMAN_PLUSHIE_BLOCK_ENTITY,
				context -> new PlushieRenderer(Identifier.of(Plushified.MOD_ID, "checkgoodman_plushie")));
		BlockEntityRendererFactories.register(CLOWNPIERCE_PLUSHIE_BLOCK_ENTITY,
				context -> new PlushieRenderer(Identifier.of(Plushified.MOD_ID, "clownpierce_plushie")));
		BlockEntityRendererFactories.register(DEB_PLUSHIE_BLOCK_ENTITY,
				context -> new PlushieRenderer(Identifier.of(Plushified.MOD_ID, "deb_plushie")));
		BlockEntityRendererFactories.register(DIANSU_PLUSHIE_BLOCK_ENTITY,
				context -> new PlushieRenderer(Identifier.of(Plushified.MOD_ID, "diansu_plushie")));
		BlockEntityRendererFactories.register(DLZ_PLUSHIE_BLOCK_ENTITY,
				context -> new PlushieRenderer(Identifier.of(Plushified.MOD_ID, "dlz_plushie")));
		BlockEntityRendererFactories.register(DOCTOR4T_PLUSHIE_BLOCK_ENTITY,
				context -> new PlushieRenderer(Identifier.of(Plushified.MOD_ID, "doctor4t_plushie")));
		BlockEntityRendererFactories.register(DURAWKA_PLUSHIE_BLOCK_ENTITY,
				context -> new PlushieRenderer(Identifier.of(Plushified.MOD_ID, "durawka_plushie")));
		BlockEntityRendererFactories.register(EBONI_PLUSHIE_BLOCK_ENTITY,
				context -> new PlushieRenderer(Identifier.of(Plushified.MOD_ID, "eboni_plushie")));
		BlockEntityRendererFactories.register(FELIKTON_PLUSHIE_BLOCK_ENTITY,
				context -> new PlushieRenderer(Identifier.of(Plushified.MOD_ID, "felikton_plushie")));
		BlockEntityRendererFactories.register(FEREDEN_PLUSHIE_BLOCK_ENTITY,
				context -> new PlushieRenderer(Identifier.of(Plushified.MOD_ID, "fereden_plushie")));
		BlockEntityRendererFactories.register(FINEK_PLUSHIE_BLOCK_ENTITY,
				context -> new PlushieRenderer(Identifier.of(Plushified.MOD_ID, "finek_plushie")));
		BlockEntityRendererFactories.register(GOOSE_PLUSHIE_BLOCK_ENTITY,
				context -> new PlushieRenderer(Identifier.of(Plushified.MOD_ID, "goose_plushie")));
		BlockEntityRendererFactories.register(LAMPCAT_PLUSHIE_BLOCK_ENTITY,
				context -> new PlushieRenderer(Identifier.of(Plushified.MOD_ID, "lampcat_plushie")));
		BlockEntityRendererFactories.register(LUX_PLUSHIE_BLOCK_ENTITY,
				context -> new PlushieRenderer(Identifier.of(Plushified.MOD_ID, "lux_plushie")));
		BlockEntityRendererFactories.register(MASK_PLUSHIE_BLOCK_ENTITY,
				context -> new PlushieRenderer(Identifier.of(Plushified.MOD_ID, "mask_plushie")));
		BlockEntityRendererFactories.register(MODDY_PLUSHIE_BLOCK_ENTITY,
				context -> new PlushieRenderer(Identifier.of(Plushified.MOD_ID, "moddy_plushie")));
		BlockEntityRendererFactories.register(NIKI_PLUSHIE_BLOCK_ENTITY,
				context -> new PlushieRenderer(Identifier.of(Plushified.MOD_ID, "niki_plushie")));
		BlockEntityRendererFactories.register(NOVIKONY_PLUSHIE_BLOCK_ENTITY,
				context -> new PlushieRenderer(Identifier.of(Plushified.MOD_ID, "novikony_plushie")));
		BlockEntityRendererFactories.register(OBSI_PLUSHIE_BLOCK_ENTITY,
				context -> new PlushieRenderer(Identifier.of(Plushified.MOD_ID, "obsi_plushie")));
		BlockEntityRendererFactories.register(PHILZA_PLUSHIE_BLOCK_ENTITY,
				context -> new PlushieRenderer(Identifier.of(Plushified.MOD_ID, "philza_plushie")));
		BlockEntityRendererFactories.register(PWGOOD_PLUSHIE_BLOCK_ENTITY,
				context -> new PlushieRenderer(Identifier.of(Plushified.MOD_ID, "pwgood_plushie")));
		BlockEntityRendererFactories.register(R4TMAID_PLUSHIE_BLOCK_ENTITY,
				context -> new PlushieRenderer(Identifier.of(Plushified.MOD_ID, "r4tmaid_plushie")));
		BlockEntityRendererFactories.register(RANBOO_PLUSHIE_BLOCK_ENTITY,
				context -> new PlushieRenderer(Identifier.of(Plushified.MOD_ID, "ranboo_plushie")));
		BlockEntityRendererFactories.register(RESOTA_PLUSHIE_BLOCK_ENTITY,
				context -> new PlushieRenderer(Identifier.of(Plushified.MOD_ID, "resota_plushie")));
		BlockEntityRendererFactories.register(SQUIDDO_PLUSHIE_BLOCK_ENTITY,
				context -> new PlushieRenderer(Identifier.of(Plushified.MOD_ID, "squiddo_plushie")));
		BlockEntityRendererFactories.register(STALIN_PLUSHIE_BLOCK_ENTITY,
				context -> new PlushieRenderer(Identifier.of(Plushified.MOD_ID, "stalin_plushie")));
		BlockEntityRendererFactories.register(TECHNO_PLUSHIE_BLOCK_ENTITY,
				context -> new PlushieRenderer(Identifier.of(Plushified.MOD_ID, "techno_plushie")));
		BlockEntityRendererFactories.register(TUVIKU_PLUSHIE_BLOCK_ENTITY,
				context -> new PlushieRenderer(Identifier.of(Plushified.MOD_ID, "tuviku_plushie")));
		BlockEntityRendererFactories.register(VERYLOUDER_PLUSHIE_BLOCK_ENTITY,
				context -> new PlushieRenderer(Identifier.of(Plushified.MOD_ID, "verylouder_plushie")));
		BlockEntityRendererFactories.register(VMUTED_PLUSHIE_BLOCK_ENTITY,
				context -> new PlushieRenderer(Identifier.of(Plushified.MOD_ID, "vmuted_plushie")));
		BlockEntityRendererFactories.register(WINSWEEP_PLUSHIE_BLOCK_ENTITY,
				context -> new PlushieRenderer(Identifier.of(Plushified.MOD_ID, "winsweep_plushie")));
		BlockEntityRendererFactories.register(ZMEEC_PLUSHIE_BLOCK_ENTITY,
				context -> new PlushieRenderer(Identifier.of(Plushified.MOD_ID, "zmeec_plushie")));
		BlockEntityRendererFactories.register(ZMEEVIG_PLUSHIE_BLOCK_ENTITY,
				context -> new PlushieRenderer(Identifier.of(Plushified.MOD_ID, "zmeevig_plushie")));
		BlockEntityRendererFactories.register(JEREMI_PLUSHIE_BLOCK_ENTITY,
				context -> new PlushieRenderer(Identifier.of(Plushified.MOD_ID, "jeremi_plushie")));
		BlockEntityRendererFactories.register(NUROFEN_PLUSHIE_BLOCK_ENTITY,
				context -> new PlushieRenderer(Identifier.of(Plushified.MOD_ID, "nurofen_plushie"))); //this comment is autogenerated
	}
}