package net.plushified.datagen.translation;

import net.fabricmc.fabric.api.datagen.v1.FabricDataOutput;
import net.fabricmc.fabric.api.datagen.v1.provider.FabricLanguageProvider;
import net.minecraft.registry.RegistryWrapper;
import net.plushified.Plushified;

import java.nio.file.Path;
import java.util.Optional;
import java.util.concurrent.CompletableFuture;

import static net.plushified.registry.BlockRegistry.*;

public class EnglishTranslationGenerator extends FabricLanguageProvider {
    public EnglishTranslationGenerator(FabricDataOutput dataOutput, CompletableFuture<RegistryWrapper.WrapperLookup> registryLookup) {
        super(dataOutput, registryLookup);
    }

    @Override
    public void generateTranslations(RegistryWrapper.WrapperLookup registryLookup, TranslationBuilder translationBuilder) {
        translationBuilder.add(ALEXNOMPE_PLUSHIE, "Alexnompe plushie");
        translationBuilder.add(ARUYUKI_PLUSHIE, "Aruyuki plushie");
        translationBuilder.add(BADBOYHALO_PLUSHIE, "Badboyhalo plushie");
        translationBuilder.add(BLACKHOLE_PLUSHIE, "Blackhole plushie");
        translationBuilder.add(BRIM_PLUSHIE, "Brim plushie");
        translationBuilder.add(CHECKGOODMAN_PLUSHIE, "Checkgoodman plushie");
        translationBuilder.add(CLOWNPIERCE_PLUSHIE, "Clownpierce plushie");
        translationBuilder.add(DEB_PLUSHIE, "Deb plushie");
        translationBuilder.add(DIANSU_PLUSHIE, "Diansu plushie");
        translationBuilder.add(DLZ_PLUSHIE, "Dlz plushie");
        translationBuilder.add(DOCTOR4T_PLUSHIE, "Doctor4t plushie");
        translationBuilder.add(DURAWKA_PLUSHIE, "Durawka plushie");
        translationBuilder.add(EBONI_PLUSHIE, "Eboni plushie");
        translationBuilder.add(FELIKTON_PLUSHIE, "Felikton plushie");
        translationBuilder.add(FEREDEN_PLUSHIE, "Fereden plushie");
        translationBuilder.add(FINEK_PLUSHIE, "Finek plushie");
        translationBuilder.add(GOOSE_PLUSHIE, "Goose plushie");
        translationBuilder.add(JEREMI_PLUSHIE, "Jeremi plushie");
        translationBuilder.add(LAMPCAT_PLUSHIE, "Lampcat plushie");
        translationBuilder.add(LUX_PLUSHIE, "Lux plushie");
        translationBuilder.add(MASK_PLUSHIE, "Mask plushie");
        translationBuilder.add(MODDY_PLUSHIE, "Moddy plushie");
        translationBuilder.add(NIKI_PLUSHIE, "Niki plushie");
        translationBuilder.add(NOVIKONY_PLUSHIE, "Novikony plushie");
        translationBuilder.add(NUROFEN_PLUSHIE, "Nurofen plushie");
        translationBuilder.add(OBSI_PLUSHIE, "Obsi plushie");
        translationBuilder.add(PHILZA_PLUSHIE, "Philza plushie");
        translationBuilder.add(PWGOOD_PLUSHIE, "Pwgood plushie");
        translationBuilder.add(R4TMAID_PLUSHIE, "R4tmaid plushie");
        translationBuilder.add(RANBOO_PLUSHIE, "Ranboo plushie");
        translationBuilder.add(RESOTA_PLUSHIE, "Resota plushie");
        translationBuilder.add(SQUIDDO_PLUSHIE, "Squiddo plushie");
        translationBuilder.add(STALIN_PLUSHIE, "Stalin plushie");
        translationBuilder.add(TECHNO_PLUSHIE, "Techno plushie");
        translationBuilder.add(TUVIKU_PLUSHIE, "Tuviku plushie");
        translationBuilder.add(VERYLOUDER_PLUSHIE, "Verylouder plushie");
        translationBuilder.add(VMUTED_PLUSHIE, "Vmuted plushie");
        translationBuilder.add(WINSWEEP_PLUSHIE, "Winsweep plushie");
        translationBuilder.add(ZMEEC_PLUSHIE, "Zmeec plushie");
        translationBuilder.add(ZMEEVIG_PLUSHIE, "Zmeevig plushie"); //this comment is autogenerated

        translationBuilder.add("itemGroup."+Plushified.MOD_ID+".plushies", "Plushies");

        translationBuilder.add("subtitles."+Plushified.MOD_ID+".plushie_pat_sound", "Plushie squeak");

        try {
            Optional<Path> path = dataOutput.getModContainer().findPath("assets/plushified/lang/en_us.json");
            translationBuilder.add(path.get());
        } catch (Exception e) {
            LOGGER.info("Failed to merge language file: " + e);
        }
    }
}
