package net.plushified.datagen.translation;

import net.fabricmc.fabric.api.datagen.v1.FabricDataOutput;
import net.fabricmc.fabric.api.datagen.v1.provider.FabricLanguageProvider;
import net.minecraft.registry.RegistryWrapper;
import net.plushified.Plushified;

import java.nio.file.Path;
import java.util.Optional;
import java.util.concurrent.CompletableFuture;

import static net.plushified.registry.BlockRegistry.*;

public class RussianTranslationGenerator extends FabricLanguageProvider {
    public RussianTranslationGenerator(FabricDataOutput dataOutput, CompletableFuture<RegistryWrapper.WrapperLookup> registryLookup) {
        super(dataOutput, "ru_ru", registryLookup);
    }

    @Override
    public void generateTranslations(RegistryWrapper.WrapperLookup registryLookup, TranslationBuilder translationBuilder) {
        translationBuilder.add(ALEXNOMPE_PLUSHIE, "Плюшевая игрушка AlexNompe");
        translationBuilder.add(ARUYUKI_PLUSHIE, "Плюшевая игрушка Aruyuki");
        translationBuilder.add(BADBOYHALO_PLUSHIE, "Плюшевая игрушка Badboyhalo");
        translationBuilder.add(BLACKHOLE_PLUSHIE, "Плюшевая игрушка Blackhole");
        translationBuilder.add(BRIM_PLUSHIE, "Плюшевая игрушка Brim");
        translationBuilder.add(CHECKGOODMAN_PLUSHIE, "Плюшевая игрушка Checkgoodman");
        translationBuilder.add(CLOWNPIERCE_PLUSHIE, "Плюшевая игрушка Clownpierce");
        translationBuilder.add(DEB_PLUSHIE, "Плюшевая игрушка Deb");
        translationBuilder.add(DIANSU_PLUSHIE, "Плюшевая игрушка Diansu");
        translationBuilder.add(DLZ_PLUSHIE, "Плюшевая игрушка Dlz");
        translationBuilder.add(DOCTOR4T_PLUSHIE, "Плюшевая игрушка Doctor4t");
        translationBuilder.add(DURAWKA_PLUSHIE, "Плюшевая игрушка Durawka");
        translationBuilder.add(EBONI_PLUSHIE, "Плюшевая игрушка Eboni");
        translationBuilder.add(FELIKTON_PLUSHIE, "Плюшевая игрушка Felikton");
        translationBuilder.add(FEREDEN_PLUSHIE, "Плюшевая игрушка Fereden");
        translationBuilder.add(FINEK_PLUSHIE, "Плюшевая игрушка Finek");
        translationBuilder.add(GOOSE_PLUSHIE, "Плюшевая игрушка Goose");
        translationBuilder.add(JEREMI_PLUSHIE, "Плюшевая игрушка Jeremi");
        translationBuilder.add(LAMPCAT_PLUSHIE, "Плюшевая игрушка Lampcat");
        translationBuilder.add(LUX_PLUSHIE, "Плюшевая игрушка Lux");
        translationBuilder.add(MASK_PLUSHIE, "Плюшевая игрушка Mask");
        translationBuilder.add(MODDY_PLUSHIE, "Плюшевая игрушка Moddy");
        translationBuilder.add(NIKI_PLUSHIE, "Плюшевая игрушка Niki");
        translationBuilder.add(NOVIKONY_PLUSHIE, "Плюшевая игрушка Novikony");
        translationBuilder.add(NUROFEN_PLUSHIE, "Плюшевая игрушка Nurofen");
        translationBuilder.add(OBSI_PLUSHIE, "Плюшевая игрушка Obsi");
        translationBuilder.add(PHILZA_PLUSHIE, "Плюшевая игрушка Philza");
        translationBuilder.add(PWGOOD_PLUSHIE, "Плюшевая игрушка Pwgood");
        translationBuilder.add(R4TMAID_PLUSHIE, "Плюшевая игрушка R4tmaid");
        translationBuilder.add(RANBOO_PLUSHIE, "Плюшевая игрушка Ranboo");
        translationBuilder.add(RESOTA_PLUSHIE, "Плюшевая игрушка Resota");
        translationBuilder.add(SQUIDDO_PLUSHIE, "Плюшевая игрушка Squiddo");
        translationBuilder.add(STALIN_PLUSHIE, "Плюшевая игрушка Stalin");
        translationBuilder.add(TECHNO_PLUSHIE, "Плюшевая игрушка Techno");
        translationBuilder.add(TUVIKU_PLUSHIE, "Плюшевая игрушка Tuviku");
        translationBuilder.add(VERYLOUDER_PLUSHIE, "Плюшевая игрушка Verylouder");
        translationBuilder.add(VMUTED_PLUSHIE, "Плюшевая игрушка Vmuted");
        translationBuilder.add(WINSWEEP_PLUSHIE, "Плюшевая игрушка Winsweep");
        translationBuilder.add(ZMEEC_PLUSHIE, "Плюшевая игрушка Zmeec");
        translationBuilder.add(ZMEEVIG_PLUSHIE, "Плюшевая игрушка Zmeevig"); //this comment is autogenerated

        translationBuilder.add("itemGroup."+ Plushified.MOD_ID+".plushies", "Плюшевые игрушки");

        translationBuilder.add("subtitles."+Plushified.MOD_ID+".plushie_pat_sound", "Писк плюшевой игрушки");

        try {
            Optional<Path> path = dataOutput.getModContainer().findPath("assets/plushified/lang/ru_ru.json");
            translationBuilder.add(path.get());
        } catch (Exception e) {
            LOGGER.info("Failed to merge language file: " + e);
        }
    }
}
