import os

import minecraft_advanced_plushie_generator

limit = 111
capital_name = ""
lowercase_name = ""

i = 0

path = os.path.realpath("minecraft_advanced_plushie_generator.py").replace(r"\python\minecraft_advanced_plushie_generator.py",r"")


def format_new_name(string):
    global capital_name
    global lowercase_name
    return string.replace("ALEXNOMPE", capital_name).replace("alexnompe", lowercase_name).replace("AlexNompe",
                                                                                                  lowercase_name.capitalize())


def insert_plushie_into_the_game(name):
    global limit
    global capital_name
    global lowercase_name
    global path

    global i

    capital_name = name.swapcase()
    lowercase_name = name.lower()

    i = 0

    text = ""
    with open(rf"{path}\src\client\java\net\plushified\PlushifiedClient.java",
              "r+") as file:
        check = """_plushie")));
		BlockEntityRendererFactories.register(ALEXNOMPE_PLUSHIE_BLOCK_ENTITY,
				context -> new PlushieRenderer(Identifier.of(Plushified.MOD_ID, "alexnompe_plushie"))); //this comment is autogenerated""".replace(
            "ALEXNOMPE", capital_name).replace("alexnompe", lowercase_name).replace("AlexNompe",
                                                                                    lowercase_name.capitalize())
        read = file.read()
        if format_new_name("""BlockEntityRendererFactories.register(ALEXNOMPE_PLUSHIE_BLOCK_ENTITY,
				context -> new PlushieRenderer(Identifier.of(Plushified.MOD_ID, "alexnompe_plushie")));""") not in read:
            text = read.replace("""_plushie"))); //this comment is autogenerated""", check, 1)
    if text != "":
        with open(rf"{path}\src\client\java\net\plushified\PlushifiedClient.java",
                  "w+") as file:
            file.write(text)
        i = 1

    text = ""
    with open(rf"{path}\src\client\java\net\plushified\PlushifiedClient.java", "r+",
              encoding='utf-8') as file:
        check = """_PLUSHIE, RenderLayer.getTranslucent());
    	BlockRenderLayerMap.INSTANCE.putBlock(ALEXNOMPE_PLUSHIE, RenderLayer.getTranslucent()); //this comment is autogenerated""".replace(
            "ALEXNOMPE", capital_name)
        read = file.read()
        if format_new_name(
                """BlockRenderLayerMap.INSTANCE.putBlock(ALEXNOMPE_PLUSHIE, RenderLayer.getTranslucent());""") not in read:
            text = read.replace("""_PLUSHIE, RenderLayer.getTranslucent()); //this comment is autogenerated""", check,
                                1)
    if text != "":
        with open(rf"{path}\src\client\java\net\plushified\PlushifiedClient.java",
                  "w+", encoding='utf-8') as file:
            file.write(text)
        i = 1

    text = ""
    with open(
            rf"{path}\src\main\java\net\plushified\datagen\translation\EnglishTranslationGenerator.java",
            "r+") as file:
        check = """plushie");
        translationBuilder.add(ALEXNOMPE_PLUSHIE, "AlexNompe plushie"); //this comment is autogenerated""".replace(
            "ALEXNOMPE", capital_name).replace("AlexNompe", lowercase_name.capitalize())
        read = file.read()
        if format_new_name("""translationBuilder.add(ALEXNOMPE_PLUSHIE,""") not in read:
            text = read.replace("""plushie"); //this comment is autogenerated""", check, 1)
    if text != "":
        with open(
                rf"{path}\src\main\java\net\plushified\datagen\translation\EnglishTranslationGenerator.java",
                "w+") as file:
            file.write(text)
        i = 1

    text = ""
    with open(
            rf"{path}\src\main\java\net\plushified\datagen\translation\RussianTranslationGenerator.java",
            "r+", encoding='utf-8') as file:
        check = """");
        translationBuilder.add(ALEXNOMPE_PLUSHIE, "Плюшевая игрушка AlexNompe"); //this comment is autogenerated""".replace(
            "ALEXNOMPE", capital_name).replace("AlexNompe", lowercase_name.capitalize())
        read = file.read()
        if format_new_name("""translationBuilder.add(ALEXNOMPE_PLUSHIE,""") not in read:
            text = read.replace(""""); //this comment is autogenerated""", check, 1)
    if text != "":
        with open(
                rf"{path}\src\main\java\net\plushified\datagen\translation\RussianTranslationGenerator.java",
                "w+", encoding='utf-8') as file:
            file.write(text)
        i = 1

    text = ""
    with open(
            rf"{path}\src\main\java\net\plushified\datagen\BlockLootTableGenerator.java",
            "r+", encoding='utf-8') as file:
        check = """_PLUSHIE));
        addDrop(ALEXNOMPE_PLUSHIE, drops(ALEXNOMPE_PLUSHIE)); //this comment is autogenerated""".replace("ALEXNOMPE",
                                                                                                         capital_name)
        read = file.read()
        if format_new_name("""addDrop(ALEXNOMPE_PLUSHIE, drops(ALEXNOMPE_PLUSHIE));""") not in read:
            text = read.replace("""_PLUSHIE)); //this comment is autogenerated""", check, 1)
    if text != "":
        with open(
                rf"{path}\src\main\java\net\plushified\datagen\BlockLootTableGenerator.java",
                "w+", encoding='utf-8') as file:
            file.write(text)
        i = 1

    text = ""
    with open(rf"{path}\src\main\java\net\plushified\datagen\BlockTagGenerator.java",
              "r+", encoding='utf-8') as file:
        check = """_PLUSHIE)
                .add(ALEXNOMPE_PLUSHIE);""".replace("ALEXNOMPE", capital_name)
        read = file.read()
        if format_new_name(""".add(ALEXNOMPE_PLUSHIE)""") not in read:
            text = read.replace("""_PLUSHIE);""", check, 1)
    if text != "":
        with open(rf"{path}\src\main\java\net\plushified\datagen\BlockTagGenerator.java",
                  "w+", encoding='utf-8') as file:
            file.write(text)
        i = 1

    text = ""
    with open(rf"{path}\src\main\java\net\plushified\datagen\ModelGenerator.java", "r+",
              encoding='utf-8') as file:
        check = """_plushie")), Optional.empty()));
        itemModelGenerator.register(ALEXNOMPE_PLUSHIE.asItem(), new Model(Optional.of(Identifier.of(Plushified.MOD_ID,"block/alexnompe_plushie")), Optional.empty())); //this comment is autogenerated""".replace(
            "ALEXNOMPE", capital_name).replace("alexnompe", lowercase_name)
        read = file.read()
        if format_new_name(
                """itemModelGenerator.register(ALEXNOMPE_PLUSHIE.asItem(), new Model(Optional.of(Identifier.of(Plushified.MOD_ID,"block/alexnompe_plushie")), Optional.empty()));""") not in read:
            text = read.replace("""_plushie")), Optional.empty())); //this comment is autogenerated""", check, 1)
    if text != "":
        with open(rf"{path}\src\main\java\net\plushified\datagen\ModelGenerator.java",
                  "w+", encoding='utf-8') as file:
            file.write(text)
        i = 1

    text = ""
    with open(rf"{path}\src\main\java\net\plushified\datagen\ModelGenerator.java", "r+",
              encoding='utf-8') as file:
        check = """_plushie");
                variants.add("", model);
                json.add("variants", variants);
                return json;
            }
        });
        blockStateModelGenerator.blockStateCollector.accept(new BlockStateSupplier() {
            @Override
            public Block getBlock() {
                return ALEXNOMPE_PLUSHIE;
            }
            @Override
            public JsonElement get() {
                JsonObject json = new JsonObject();
                JsonObject variants = new JsonObject();
                JsonObject model = new JsonObject();
                model.addProperty("model", Plushified.MOD_ID+":block/alexnompe_plushie");
                variants.add("", model);
                json.add("variants", variants);
                return json;
            }
        }); //this comment is autogenerated""".replace(
            "ALEXNOMPE", capital_name).replace("alexnompe", lowercase_name)
        read = file.read()
        if format_new_name(
                """@Override
            public Block getBlock() {
                return ALEXNOMPE_PLUSHIE;
            }""") not in read:
            text = read.replace("""_plushie");
                variants.add("", model);
                json.add("variants", variants);
                return json;
            }
        }); //this comment is autogenerated""", check, 1)
    if text != "":
        with open(rf"{path}\src\main\java\net\plushified\datagen\ModelGenerator.java",
                  "w+", encoding='utf-8') as file:
            file.write(text)
        i = 1

    text = ""
    with open(rf"{path}\src\main\java\net\plushified\registry\BlockEntityRegistry.java",
              "r+", encoding='utf-8') as file:
        check = """_PLUSHIE_BLOCK_ENTITY, pos, state);
        }
    }
    public static class AlexNompePlushieBlockEntity extends PlushieBlockEntity {

        public AlexNompePlushieBlockEntity(BlockPos pos, BlockState state) {
            super(ALEXNOMPE_PLUSHIE_BLOCK_ENTITY, pos, state);
        }
    } //this comment is autogenerated""".replace("ALEXNOMPE", capital_name).replace("AlexNompe",
                                                                                    lowercase_name.capitalize())
        read = file.read()
        if format_new_name("""super(ALEXNOMPE_PLUSHIE_BLOCK_ENTITY, pos, state);""") not in read:
            text = read.replace("""_PLUSHIE_BLOCK_ENTITY, pos, state);
        }
    } //this comment is autogenerated""", check, 1)
    if text != "":
        with open(
                rf"{path}\src\main\java\net\plushified\registry\BlockEntityRegistry.java",
                "w+", encoding='utf-8') as file:
            file.write(text)
        i = 1

    text = ""
    with open(rf"{path}\src\main\java\net\plushified\registry\BlockEntityRegistry.java",
              "r+", encoding='utf-8') as file:
        check = """_PLUSHIE).build();
    public static final BlockEntityType<AlexNompePlushieBlockEntity> ALEXNOMPE_PLUSHIE_BLOCK_ENTITY = BlockEntityType.Builder.create(AlexNompePlushieBlockEntity::new, ALEXNOMPE_PLUSHIE).build(); //this comment is autogenerated""".replace(
            "ALEXNOMPE", capital_name).replace("AlexNompe", lowercase_name.capitalize())
        read = file.read()
        if format_new_name("""ALEXNOMPE_PLUSHIE_BLOCK_ENTITY = BlockEntityType.Builder.create(""") not in read:
            text = read.replace("""_PLUSHIE).build(); //this comment is autogenerated""", check, 1)
    if text != "":
        with open(
                rf"{path}\src\main\java\net\plushified\registry\BlockEntityRegistry.java",
                "w+", encoding='utf-8') as file:
            file.write(text)
        i = 1

    text = ""
    with open(rf"{path}\src\main\java\net\plushified\registry\BlockEntityRegistry.java",
              "r+", encoding='utf-8') as file:
        check = """_PLUSHIE_BLOCK_ENTITY);
        Registry.register(Registries.BLOCK_ENTITY_TYPE,
                Identifier.of(Plushified.MOD_ID, "alexnompe_plushie_block_entity"),
                ALEXNOMPE_PLUSHIE_BLOCK_ENTITY); //this comment is autogenerated""".replace("ALEXNOMPE",
                                                                                            capital_name).replace(
            "alexnompe", lowercase_name)
        read = file.read()
        if format_new_name("""Registry.register(Registries.BLOCK_ENTITY_TYPE,
                Identifier.of(Plushified.MOD_ID, "alexnompe_plushie_block_entity"),
                ALEXNOMPE_PLUSHIE_BLOCK_ENTITY);""") not in read:
            text = read.replace("""_PLUSHIE_BLOCK_ENTITY); //this comment is autogenerated""", check, 1)
    if text != "":
        with open(
                rf"{path}\src\main\java\net\plushified\registry\BlockEntityRegistry.java",
                "w+", encoding='utf-8') as file:
            file.write(text)
        i = 1

    text = ""
    with open(rf"{path}\src\main\java\net\plushified\registry\BlockRegistry.java", "r+",
              encoding='utf-8') as file:
        check = """PlushieBlockEntity::tick);
        }
    };
    public static final Block ALEXNOMPE_PLUSHIE = new Plushie(Block.Settings.create().strength(1.0f).sounds(PLUSHIE_SOUND_GROUP)) {
        @Override
        public @NotNull BlockEntity createBlockEntity(BlockPos pos, BlockState state) {
            return new AlexNompePlushieBlockEntity(pos, state);
        }
        @Nullable
        @Override
        public <T extends BlockEntity> BlockEntityTicker<T> getTicker(World world, BlockState state, BlockEntityType<T> type) {
            return validateTicker(type, ALEXNOMPE_PLUSHIE_BLOCK_ENTITY,
                    AlexNompePlushieBlockEntity::tick);
        }
    }; //this comment is autogenerated""".replace("ALEXNOMPE", capital_name).replace("AlexNompe",
                                                                                     lowercase_name.capitalize())
        read = file.read()
        if format_new_name(
                """public static final Block ALEXNOMPE_PLUSHIE = new Plushie(Block.Settings.create()""") not in read:
            text = read.replace("""PlushieBlockEntity::tick);
        }
    }; //this comment is autogenerated""", check, 1)
    if text != "":
        with open(rf"{path}\src\main\java\net\plushified\registry\BlockRegistry.java",
                  "w+", encoding='utf-8') as file:
            file.write(text)
        i = 1

    text = ""
    with open(rf"{path}\src\main\java\net\plushified\registry\BlockRegistry.java", "r+",
              encoding='utf-8') as file:
        check = """_PLUSHIE);
        RegisterBlockItem(Identifier.of(Plushified.MOD_ID, "alexnompe_plushie"), ALEXNOMPE_PLUSHIE); //this comment is autogenerated""".replace(
            "ALEXNOMPE", capital_name).replace("alexnompe", lowercase_name)
        read = file.read()
        if format_new_name(
                """RegisterBlockItem(Identifier.of(Plushified.MOD_ID, "alexnompe_plushie"), ALEXNOMPE_PLUSHIE);""") not in read:
            text = read.replace("""_PLUSHIE); //this comment is autogenerated""", check, 1)
    if text != "":
        with open(rf"{path}\src\main\java\net\plushified\registry\BlockRegistry.java",
                  "w+", encoding='utf-8') as file:
            file.write(text)
        i = 1

    text = ""
    with open(rf"{path}\src\main\java\net\plushified\registry\ItemGroupRegistry.java",
              "r+",
              encoding='utf-8') as file:
        check = """_PLUSHIE);
                entries.add(ALEXNOMPE_PLUSHIE); //this comment is autogenerated""".replace(
            "ALEXNOMPE", capital_name).replace("alexnompe", lowercase_name)
        read = file.read()
        if format_new_name(
                """entries.add(ALEXNOMPE_PLUSHIE);""") not in read:
            text = read.replace("""_PLUSHIE); //this comment is autogenerated""", check, 1)
    if text != "":
        with open(
                rf"{path}\src\main\java\net\plushified\registry\ItemGroupRegistry.java",
                "w+", encoding='utf-8') as file:
            file.write(text)
        i = 1

    contents = ""
    with open(
            rf"{path}\src\main\resources\assets\plushified\geo\block\alexnompe_plushie.geo.json",
            "r+", encoding='utf-8') as file:
        contents = file.read()
    try:
        with open(
                rf"{path}\src\main\resources\assets\plushified\geo\block\{lowercase_name}_plushie.geo.json",
                "x") as f:
            f.write(contents)
            i = 1
    except FileExistsError:
        pass

    contents = ""
    with open(
            rf"{path}\src\main\resources\assets\plushified\models\block\alexnompe_plushie.json",
            "r+", encoding='utf-8') as file:
        contents = file.read().replace("alexnompe", lowercase_name)
    try:
        with open(
                rf"{path}\src\main\resources\assets\plushified\models\block\{lowercase_name}_plushie.json",
                "x") as f:
            f.write(contents)
            i = 1
    except FileExistsError:
        pass

    contents = ""
    with open(
            rf"{path}\src\main\resources\assets\plushified\models\custom\alexnompe_plushie.json",
            "r+", encoding='utf-8') as file:
        contents = file.read().replace("alexnompe", lowercase_name)
    try:
        with open(
                rf"{path}\src\main\resources\assets\plushified\models\custom\{lowercase_name}_plushie.json",
                "x") as f:
            f.write(contents)
            i = 1
    except FileExistsError:
        pass

    if i == 1: print(f"Done with {name.capitalize()}")
    limit -= i


def remove_plushie(name):
    global limit
    global capital_name
    global lowercase_name
    global path
    global i

    capital_name = name.swapcase()
    lowercase_name = name.lower()

    i = 0

    text = ""
    with open(rf"{path}\src\client\java\net\plushified\PlushifiedClient.java",
              "r+") as file:
        check = """_plushie")));
		BlockEntityRendererFactories.register(ALEXNOMPE_PLUSHIE_BLOCK_ENTITY,
				context -> new PlushieRenderer(Identifier.of(Plushified.MOD_ID, "alexnompe_plushie"))); //this comment is autogenerated""".replace(
            "ALEXNOMPE", capital_name).replace("alexnompe", lowercase_name).replace("AlexNompe",
                                                                                    lowercase_name.capitalize())
        read = file.read()
        if format_new_name("""BlockEntityRendererFactories.register(ALEXNOMPE_PLUSHIE_BLOCK_ENTITY,
				context -> new PlushieRenderer(Identifier.of(Plushified.MOD_ID, "alexnompe_plushie")));""") in read:
            text = read.replace(check, """_plushie"))); //this comment is autogenerated""", 1)
    if text != "":
        with open(rf"{path}\src\client\java\net\plushified\PlushifiedClient.java",
                  "w+") as file:
            file.write(text)
        i = 1

    text = ""
    with open(rf"{path}\src\client\java\net\plushified\PlushifiedClient.java", "r+",
              encoding='utf-8') as file:
        check = """_PLUSHIE, RenderLayer.getTranslucent());
    	BlockRenderLayerMap.INSTANCE.putBlock(ALEXNOMPE_PLUSHIE, RenderLayer.getTranslucent()); //this comment is autogenerated""".replace(
            "ALEXNOMPE", capital_name)
        read = file.read()
        if format_new_name(
                """BlockRenderLayerMap.INSTANCE.putBlock(ALEXNOMPE_PLUSHIE, RenderLayer.getTranslucent());""") in read:
            text = read.replace(check, """_PLUSHIE, RenderLayer.getTranslucent()); //this comment is autogenerated""",
                                1)
    if text != "":
        with open(rf"{path}\src\client\java\net\plushified\PlushifiedClient.java",
                  "w+", encoding='utf-8') as file:
            file.write(text)
        i = 1

    text = ""
    with open(
            rf"{path}\src\main\java\net\plushified\datagen\translation\EnglishTranslationGenerator.java",
            "r+") as file:
        check = """plushie");
        translationBuilder.add(ALEXNOMPE_PLUSHIE, "AlexNompe plushie"); //this comment is autogenerated""".replace(
            "ALEXNOMPE", capital_name).replace("AlexNompe", lowercase_name.capitalize())
        read = file.read()
        if format_new_name("""translationBuilder.add(ALEXNOMPE_PLUSHIE,""") in read:
            text = read.replace(check, """plushie"); //this comment is autogenerated""", 1)
    if text != "":
        with open(
                rf"{path}\src\main\java\net\plushified\datagen\translation\EnglishTranslationGenerator.java",
                "w+") as file:
            file.write(text)
        i = 1

    text = ""
    with open(
            rf"{path}\src\main\java\net\plushified\datagen\translation\RussianTranslationGenerator.java",
            "r+", encoding='utf-8') as file:
        check = """");
        translationBuilder.add(ALEXNOMPE_PLUSHIE, "Плюшевая игрушка AlexNompe"); //this comment is autogenerated""".replace(
            "ALEXNOMPE", capital_name).replace("AlexNompe", lowercase_name.capitalize())
        read = file.read()
        if format_new_name("""translationBuilder.add(ALEXNOMPE_PLUSHIE,""") in read:
            text = read.replace(check, """"); //this comment is autogenerated""", 1)
    if text != "":
        with open(
                rf"{path}\src\main\java\net\plushified\datagen\translation\RussianTranslationGenerator.java",
                "w+", encoding='utf-8') as file:
            file.write(text)
        i = 1

    text = ""
    with open(
            rf"{path}\src\main\java\net\plushified\datagen\BlockLootTableGenerator.java",
            "r+", encoding='utf-8') as file:
        check = """_PLUSHIE));
        addDrop(ALEXNOMPE_PLUSHIE, drops(ALEXNOMPE_PLUSHIE)); //this comment is autogenerated""".replace("ALEXNOMPE",
                                                                                                         capital_name)
        read = file.read()
        if format_new_name("""addDrop(ALEXNOMPE_PLUSHIE, drops(ALEXNOMPE_PLUSHIE));""") in read:
            text = read.replace(check, """_PLUSHIE)); //this comment is autogenerated""", 1)
    if text != "":
        with open(
                rf"{path}\src\main\java\net\plushified\datagen\BlockLootTableGenerator.java",
                "w+", encoding='utf-8') as file:
            file.write(text)
        i = 1

    text = ""
    with open(rf"{path}\src\main\java\net\plushified\datagen\BlockTagGenerator.java",
              "r+", encoding='utf-8') as file:
        check = """_PLUSHIE)
                .add(ALEXNOMPE_PLUSHIE);""".replace("ALEXNOMPE", capital_name)
        read = file.read()
        if format_new_name(""".add(ALEXNOMPE_PLUSHIE)""") in read:
            text = read.replace(check, """_PLUSHIE);""", 1)
    if text != "":
        with open(rf"{path}\src\main\java\net\plushified\datagen\BlockTagGenerator.java",
                  "w+", encoding='utf-8') as file:
            file.write(text)
        i = 1

    text = ""
    with open(rf"{path}\src\main\java\net\plushified\datagen\ModelGenerator.java", "r+",
              encoding='utf-8') as file:
        check = """_plushie")), Optional.empty()));
        itemModelGenerator.register(ALEXNOMPE_PLUSHIE.asItem(), new Model(Optional.of(Identifier.of(Plushified.MOD_ID,"block/alexnompe_plushie")), Optional.empty())); //this comment is autogenerated""".replace(
            "ALEXNOMPE", capital_name).replace("alexnompe", lowercase_name)
        read = file.read()
        if format_new_name(
                """itemModelGenerator.register(ALEXNOMPE_PLUSHIE.asItem(), new Model(Optional.of(Identifier.of(Plushified.MOD_ID,"block/alexnompe_plushie")), Optional.empty()));""") in read:
            text = read.replace(check, """_plushie")), Optional.empty())); //this comment is autogenerated""", 1)
    if text != "":
        with open(rf"{path}\src\main\java\net\plushified\datagen\ModelGenerator.java",
                  "w+", encoding='utf-8') as file:
            file.write(text)
        i = 1

    text = ""
    with open(rf"{path}\src\main\java\net\plushified\datagen\ModelGenerator.java", "r+",
              encoding='utf-8') as file:
        check = """_plushie");
                variants.add("", model);
                json.add("variants", variants);
                return json;
            }
        });
        blockStateModelGenerator.blockStateCollector.accept(new BlockStateSupplier() {
            @Override
            public Block getBlock() {
                return ALEXNOMPE_PLUSHIE;
            }
            @Override
            public JsonElement get() {
                JsonObject json = new JsonObject();
                JsonObject variants = new JsonObject();
                JsonObject model = new JsonObject();
                model.addProperty("model", Plushified.MOD_ID+":block/alexnompe_plushie");
                variants.add("", model);
                json.add("variants", variants);
                return json;
            }
        }); //this comment is autogenerated""".replace(
            "ALEXNOMPE", capital_name).replace("alexnompe", lowercase_name)
        read = file.read()
        if format_new_name(
                """@Override
            public Block getBlock() {
                return ALEXNOMPE_PLUSHIE;
            }""") in read:
            text = read.replace(check, """_plushie");
                variants.add("", model);
                json.add("variants", variants);
                return json;
            }
        }); //this comment is autogenerated""", 1)
    if text != "":
        with open(rf"{path}\src\main\java\net\plushified\datagen\ModelGenerator.java",
                  "w+", encoding='utf-8') as file:
            file.write(text)
        i = 1

    text = ""
    with open(rf"{path}\src\main\java\net\plushified\registry\BlockEntityRegistry.java",
              "r+", encoding='utf-8') as file:
        check = """_PLUSHIE_BLOCK_ENTITY, pos, state);
        }
    }
    public static class AlexNompePlushieBlockEntity extends PlushieBlockEntity {

        public AlexNompePlushieBlockEntity(BlockPos pos, BlockState state) {
            super(ALEXNOMPE_PLUSHIE_BLOCK_ENTITY, pos, state);
        }
    } //this comment is autogenerated""".replace("ALEXNOMPE", capital_name).replace("AlexNompe",
                                                                                    lowercase_name.capitalize())
        read = file.read()
        if format_new_name("""super(ALEXNOMPE_PLUSHIE_BLOCK_ENTITY, pos, state);""") in read:
            text = read.replace(check, """_PLUSHIE_BLOCK_ENTITY, pos, state);
        }
    } //this comment is autogenerated""", 1)
    if text != "":
        with open(
                rf"{path}\src\main\java\net\plushified\registry\BlockEntityRegistry.java",
                "w+", encoding='utf-8') as file:
            file.write(text)
        i = 1

    text = ""
    with open(rf"{path}\src\main\java\net\plushified\registry\BlockEntityRegistry.java",
              "r+", encoding='utf-8') as file:
        check = """_PLUSHIE).build();
    public static final BlockEntityType<AlexNompePlushieBlockEntity> ALEXNOMPE_PLUSHIE_BLOCK_ENTITY = BlockEntityType.Builder.create(AlexNompePlushieBlockEntity::new, ALEXNOMPE_PLUSHIE).build(); //this comment is autogenerated""".replace(
            "ALEXNOMPE", capital_name).replace("AlexNompe", lowercase_name.capitalize())
        read = file.read()
        if format_new_name("""ALEXNOMPE_PLUSHIE_BLOCK_ENTITY = BlockEntityType.Builder.create(""") in read:
            text = read.replace(check, """_PLUSHIE).build(); //this comment is autogenerated""", 1)
    if text != "":
        with open(
                rf"{path}\src\main\java\net\plushified\registry\BlockEntityRegistry.java",
                "w+", encoding='utf-8') as file:
            file.write(text)
        i = 1

    text = ""
    with open(rf"{path}\src\main\java\net\plushified\registry\BlockEntityRegistry.java",
              "r+", encoding='utf-8') as file:
        check = """_PLUSHIE_BLOCK_ENTITY);
        Registry.register(Registries.BLOCK_ENTITY_TYPE,
                Identifier.of(Plushified.MOD_ID, "alexnompe_plushie_block_entity"),
                ALEXNOMPE_PLUSHIE_BLOCK_ENTITY); //this comment is autogenerated""".replace("ALEXNOMPE",
                                                                                            capital_name).replace(
            "alexnompe", lowercase_name)
        read = file.read()
        if format_new_name("""Registry.register(Registries.BLOCK_ENTITY_TYPE,
                Identifier.of(Plushified.MOD_ID, "alexnompe_plushie_block_entity"),
                ALEXNOMPE_PLUSHIE_BLOCK_ENTITY);""") in read:
            text = read.replace(check, """_PLUSHIE_BLOCK_ENTITY); //this comment is autogenerated""", 1)
    if text != "":
        with open(
                rf"{path}\src\main\java\net\plushified\registry\BlockEntityRegistry.java",
                "w+", encoding='utf-8') as file:
            file.write(text)
        i = 1

    text = ""
    with open(rf"{path}\src\main\java\net\plushified\registry\BlockRegistry.java", "r+",
              encoding='utf-8') as file:
        check = """
    public static final Block ALEXNOMPE_PLUSHIE = new Plushie(Block.Settings.create().strength(1.0f).sounds(PLUSHIE_SOUND_GROUP)) {
        @Override
        public @NotNull BlockEntity createBlockEntity(BlockPos pos, BlockState state) {
            return new AlexNompePlushieBlockEntity(pos, state);
        }
        @Nullable
        @Override
        public <T extends BlockEntity> BlockEntityTicker<T> getTicker(World world, BlockState state, BlockEntityType<T> type) {
            return validateTicker(type, ALEXNOMPE_PLUSHIE_BLOCK_ENTITY,
                    AlexNompePlushieBlockEntity::tick);
        }
    }; //this comment is autogenerated""".replace("ALEXNOMPE", capital_name).replace("AlexNompe",
                                                                                     lowercase_name.capitalize())
        read = file.read()
        if format_new_name(
                """Block ALEXNOMPE_PLUSHIE = new Plushie(Block.Settings.create()""") in read:
            text = read.replace(check, """ //this comment is autogenerated""", 1)
    if text != "":
        with open(rf"{path}\src\main\java\net\plushified\registry\BlockRegistry.java",
                  "w+", encoding='utf-8') as file:
            file.write(text)
        i = 1

    text = ""
    with open(rf"{path}\src\main\java\net\plushified\registry\BlockRegistry.java", "r+",
              encoding='utf-8') as file:
        check = """_PLUSHIE);
        RegisterBlockItem(Identifier.of(Plushified.MOD_ID, "alexnompe_plushie"), ALEXNOMPE_PLUSHIE); //this comment is autogenerated""".replace(
            "ALEXNOMPE", capital_name).replace("alexnompe", lowercase_name)
        read = file.read()
        if format_new_name(
                """RegisterBlockItem(Identifier.of(Plushified.MOD_ID, "alexnompe_plushie"), ALEXNOMPE_PLUSHIE);""") in read:
            text = read.replace(check, """_PLUSHIE); //this comment is autogenerated""", 1)
    if text != "":
        with open(rf"{path}\src\main\java\net\plushified\registry\BlockRegistry.java",
                  "w+", encoding='utf-8') as file:
            file.write(text)
        i = 1

    text = ""
    with open(rf"{path}\src\main\java\net\plushified\registry\ItemGroupRegistry.java",
              "r+",
              encoding='utf-8') as file:
        check = """_PLUSHIE);
                entries.add(ALEXNOMPE_PLUSHIE); //this comment is autogenerated""".replace(
            "ALEXNOMPE", capital_name).replace("alexnompe", lowercase_name)
        read = file.read()
        if format_new_name(
                """entries.add(ALEXNOMPE_PLUSHIE);""") in read:
            text = read.replace(check, """_PLUSHIE); //this comment is autogenerated""", 1)
    if text != "":
        with open(
                rf"{path}\src\main\java\net\plushified\registry\ItemGroupRegistry.java",
                "w+", encoding='utf-8') as file:
            file.write(text)
        i = 1

    try:
        with open(
                rf"{path}\src\main\resources\assets\plushified\geo\block\{lowercase_name}_plushie.geo.json",
                "x") as f:
            pass
        os.remove(rf"{path}\src\main\resources\assets\plushified\geo\block\{lowercase_name}_plushie.geo.json")
        i = 1
    except FileExistsError:
        os.remove(rf"{path}\src\main\resources\assets\plushified\geo\block\{lowercase_name}_plushie.geo.json")
        i = 1

    try:
        with open(
                rf"{path}\src\main\resources\assets\plushified\models\block\{lowercase_name}_plushie.json",
                "x") as f:
            pass
        os.remove(rf"{path}\src\main\resources\assets\plushified\models\block\{lowercase_name}_plushie.json")
        i = 1
    except FileExistsError:
        os.remove(rf"{path}\src\main\resources\assets\plushified\models\block\{lowercase_name}_plushie.json")
        i = 1

    try:
        with open(
                rf"{path}\src\main\resources\assets\plushified\models\custom\{lowercase_name}_plushie.json",
                "x") as f:
            pass
        os.remove(rf"{path}\src\main\resources\assets\plushified\models\custom\{lowercase_name}_plushie.json")
        i = 1
    except FileExistsError:
        os.remove(rf"{path}\src\main\resources\assets\plushified\models\custom\{lowercase_name}_plushie.json")
        i = 1

    if i == 1: print(f"Done with {name.capitalize()}")
    limit -= i


def add_new_plushies(skin_path):
    global limit
    if __name__ == "__main__":
        pythonFiles = [file for dirs in os.walk(skin_path, topdown=True)
                       for file in dirs[2]]
        for r in pythonFiles:
            print(f"Checking {r}")
            if limit > 0 and not os.path.isfile((skin_path + "\\" + r).replace("_plushie", "")) and "_plushie" in str(r):
                insert_plushie_into_the_game(r.replace(".png", "").replace("_plushie", ""))


def remove_old_plushies(skin_path):
    global limit
    global i
    if __name__ == "__main__":
        pythonFiles = [file for dirs in os.walk(skin_path, topdown=True)
                       for file in dirs[2]]
        for i in range(len(pythonFiles) - 1, -1, -1):
            r = pythonFiles[i]
            print(f"Checking {r}")
            if limit > 0 and "_plushie" in str(r) and "alexnompe" not in r:
                remove_plushie(r.replace(".png", "").replace("_plushie", ""))
        if i == -1:
            remove_old_plushies(skin_path)


dir_path = rf"{path}\src\main\resources\assets\plushified\textures\block"
add_new_plushies(dir_path)
