package net.plushified.registry;

import net.fabricmc.fabric.api.itemgroup.v1.FabricItemGroup;
import net.minecraft.item.ItemGroup;
import net.minecraft.item.ItemStack;
import net.minecraft.registry.Registries;
import net.minecraft.registry.Registry;
import net.minecraft.text.Text;
import net.minecraft.util.Identifier;
import net.plushified.Plushified;

import static net.plushified.registry.BlockRegistry.*;

public class ItemGroupRegistry {
    private static final ItemGroup PLUSHIES_ITEMGROUP = FabricItemGroup.builder()
            .icon(() -> new ItemStack(ALEXNOMPE_PLUSHIE))
            .displayName(Text.translatable("itemGroup."+Plushified.MOD_ID+".plushies"))
            .entries((context, entries) -> {
                entries.add(ALEXNOMPE_PLUSHIE);
                entries.add(ARUYUKI_PLUSHIE);
                entries.add(BADBOYHALO_PLUSHIE);
                entries.add(BLACKHOLE_PLUSHIE);
                entries.add(BRIM_PLUSHIE);
                entries.add(CHECKGOODMAN_PLUSHIE);
                entries.add(CLOWNPIERCE_PLUSHIE);
                entries.add(DEB_PLUSHIE);
                entries.add(DIANSU_PLUSHIE);
                entries.add(DLZ_PLUSHIE);
                entries.add(DOCTOR4T_PLUSHIE);
                entries.add(DURAWKA_PLUSHIE);
                entries.add(EBONI_PLUSHIE);
                entries.add(FELIKTON_PLUSHIE);
                entries.add(FEREDEN_PLUSHIE);
                entries.add(FINEK_PLUSHIE);
                entries.add(GOOSE_PLUSHIE);
                entries.add(LAMPCAT_PLUSHIE);
                entries.add(LUX_PLUSHIE);
                entries.add(MASK_PLUSHIE);
                entries.add(MODDY_PLUSHIE);
                entries.add(NIKI_PLUSHIE);
                entries.add(NOVIKONY_PLUSHIE);
                entries.add(OBSI_PLUSHIE);
                entries.add(PHILZA_PLUSHIE);
                entries.add(PWGOOD_PLUSHIE);
                entries.add(R4TMAID_PLUSHIE);
                entries.add(RANBOO_PLUSHIE);
                entries.add(RESOTA_PLUSHIE);
                entries.add(SQUIDDO_PLUSHIE);
                entries.add(STALIN_PLUSHIE);
                entries.add(TECHNO_PLUSHIE);
                entries.add(TUVIKU_PLUSHIE);
                entries.add(VERYLOUDER_PLUSHIE);
                entries.add(VMUTED_PLUSHIE);
                entries.add(WINSWEEP_PLUSHIE);
                entries.add(ZMEEC_PLUSHIE);
                entries.add(ZMEEVIG_PLUSHIE);
                entries.add(JEREMI_PLUSHIE);
                entries.add(NUROFEN_PLUSHIE); //this comment is autogenerated
            })
            .build();

    public static void registering() {
        Plushified.LOGGER.info("OMG! ItemGroup registry...");
        Registry.register(Registries.ITEM_GROUP, Identifier.of(Plushified.MOD_ID, "plushies"), PLUSHIES_ITEMGROUP);
    }
}
