package net.plushified.datagen;

import net.fabricmc.fabric.api.datagen.v1.FabricDataOutput;
import net.fabricmc.fabric.api.datagen.v1.provider.FabricBlockLootTableProvider;
import net.minecraft.registry.RegistryWrapper;

import java.util.concurrent.CompletableFuture;

import static net.plushified.registry.BlockRegistry.*;

public class BlockLootTableGenerator extends FabricBlockLootTableProvider {
    public BlockLootTableGenerator(FabricDataOutput dataOutput, CompletableFuture<RegistryWrapper.WrapperLookup> registryLookup) {
        super(dataOutput, registryLookup);
    }

    @Override
    public void generate() {
        addDrop(ALEXNOMPE_PLUSHIE, drops(ALEXNOMPE_PLUSHIE));
        addDrop(ARUYUKI_PLUSHIE, drops(ARUYUKI_PLUSHIE));
        addDrop(BADBOYHALO_PLUSHIE, drops(BADBOYHALO_PLUSHIE));
        addDrop(BLACKHOLE_PLUSHIE, drops(BLACKHOLE_PLUSHIE));
        addDrop(BRIM_PLUSHIE, drops(BRIM_PLUSHIE));
        addDrop(CHECKGOODMAN_PLUSHIE, drops(CHECKGOODMAN_PLUSHIE));
        addDrop(CLOWNPIERCE_PLUSHIE, drops(CLOWNPIERCE_PLUSHIE));
        addDrop(DEB_PLUSHIE, drops(DEB_PLUSHIE));
        addDrop(DIANSU_PLUSHIE, drops(DIANSU_PLUSHIE));
        addDrop(DLZ_PLUSHIE, drops(DLZ_PLUSHIE));
        addDrop(DOCTOR4T_PLUSHIE, drops(DOCTOR4T_PLUSHIE));
        addDrop(DURAWKA_PLUSHIE, drops(DURAWKA_PLUSHIE));
        addDrop(EBONI_PLUSHIE, drops(EBONI_PLUSHIE));
        addDrop(FELIKTON_PLUSHIE, drops(FELIKTON_PLUSHIE));
        addDrop(FEREDEN_PLUSHIE, drops(FEREDEN_PLUSHIE));
        addDrop(FINEK_PLUSHIE, drops(FINEK_PLUSHIE));
        addDrop(GOOSE_PLUSHIE, drops(GOOSE_PLUSHIE));
        addDrop(JEREMI_PLUSHIE, drops(JEREMI_PLUSHIE));
        addDrop(LAMPCAT_PLUSHIE, drops(LAMPCAT_PLUSHIE));
        addDrop(LUX_PLUSHIE, drops(LUX_PLUSHIE));
        addDrop(MASK_PLUSHIE, drops(MASK_PLUSHIE));
        addDrop(MODDY_PLUSHIE, drops(MODDY_PLUSHIE));
        addDrop(NIKI_PLUSHIE, drops(NIKI_PLUSHIE));
        addDrop(NOVIKONY_PLUSHIE, drops(NOVIKONY_PLUSHIE));
        addDrop(NUROFEN_PLUSHIE, drops(NUROFEN_PLUSHIE));
        addDrop(OBSI_PLUSHIE, drops(OBSI_PLUSHIE));
        addDrop(PHILZA_PLUSHIE, drops(PHILZA_PLUSHIE));
        addDrop(PWGOOD_PLUSHIE, drops(PWGOOD_PLUSHIE));
        addDrop(R4TMAID_PLUSHIE, drops(R4TMAID_PLUSHIE));
        addDrop(RANBOO_PLUSHIE, drops(RANBOO_PLUSHIE));
        addDrop(RESOTA_PLUSHIE, drops(RESOTA_PLUSHIE));
        addDrop(SQUIDDO_PLUSHIE, drops(SQUIDDO_PLUSHIE));
        addDrop(STALIN_PLUSHIE, drops(STALIN_PLUSHIE));
        addDrop(TECHNO_PLUSHIE, drops(TECHNO_PLUSHIE));
        addDrop(TUVIKU_PLUSHIE, drops(TUVIKU_PLUSHIE));
        addDrop(VERYLOUDER_PLUSHIE, drops(VERYLOUDER_PLUSHIE));
        addDrop(VMUTED_PLUSHIE, drops(VMUTED_PLUSHIE));
        addDrop(WINSWEEP_PLUSHIE, drops(WINSWEEP_PLUSHIE));
        addDrop(ZMEEC_PLUSHIE, drops(ZMEEC_PLUSHIE));
        addDrop(ZMEEVIG_PLUSHIE, drops(ZMEEVIG_PLUSHIE)); //this comment is autogenerated
    }
}
